"""initial schema — users, projects, pdfs, extractions, qto_rows, token_events

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-04

Hand-written rather than autogenerated so it can land before any
database is available. Mirrors the DDL block in
``Plans/i-am-thinking-of-dapper-pebble.md``. ``--autogenerate`` against
this migration with the live DB should produce no diff once the schema
is applied.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "0001_initial"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users ───────────────────────────────────────────────────────
    # ``id`` is supplied by the auth middleware on first sight (set to
    # the Supabase auth.users.id). No server_default — we want the
    # auth flow to be the only path that creates rows here.
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "extraction_mode",
            sa.String(),
            nullable=False,
            server_default="multi_agent",
        ),
        sa.Column(
            "cost_saver_mode",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    # ── projects ───────────────────────────────────────────────────
    op.create_table(
        "projects",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("markup_overhead", sa.Float(), server_default="10"),
        sa.Column("markup_profit", sa.Float(), server_default="8"),
        sa.Column("markup_contingency", sa.Float(), server_default="5"),
        sa.Column(
            "exclusions",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_projects_user_id", "projects", ["user_id"])

    # ── pdfs ───────────────────────────────────────────────────────
    op.create_table(
        "pdfs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "project_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("projects.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_pdfs_project_id", "pdfs", ["project_id"])

    # ── extractions ────────────────────────────────────────────────
    op.create_table(
        "extractions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "pdf_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("pdfs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("extraction_mode", sa.String(), nullable=False),
        sa.Column(
            "cost_saver_mode",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column("cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column("total_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("api_calls", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_extractions_pdf_id", "extractions", ["pdf_id"])
    op.create_index("ix_extractions_user_id", "extractions", ["user_id"])
    op.create_index(
        "ix_extractions_user_status",
        "extractions",
        ["user_id", "status"],
    )

    # ── qto_rows ───────────────────────────────────────────────────
    op.create_table(
        "qto_rows",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "extraction_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("extractions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("s_no", sa.Integer(), nullable=True),
        sa.Column("tag", sa.String(), nullable=True),
        sa.Column("drawings", sa.String(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("qty", sa.Float(), nullable=True),
        sa.Column("units", sa.String(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("total_formula", sa.String(), nullable=True),
        sa.Column("math_trail", sa.Text(), nullable=True),
        sa.Column("trade_division", sa.String(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("source_sheet", sa.String(), nullable=True),
        sa.Column("extraction_method", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("bbox", postgresql.JSONB(), nullable=True),
        sa.Column(
            "is_header_row",
            sa.Boolean(),
            server_default=sa.text("false"),
        ),
        sa.Column("confirmed", sa.Boolean(), server_default=sa.text("false")),
        sa.Column("needs_review", sa.Boolean(), server_default=sa.text("false")),
        sa.Column(
            "risk_flags",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
    )
    op.create_index("ix_qto_rows_extraction_id", "qto_rows", ["extraction_id"])
    op.create_index("ix_qto_rows_trade_division", "qto_rows", ["trade_division"])
    op.create_index(
        "ix_qto_rows_extraction_division",
        "qto_rows",
        ["extraction_id", "trade_division"],
    )

    # ── token_events ───────────────────────────────────────────────
    op.create_table(
        "token_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "extraction_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("extractions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("api_calls", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "cache_read_tokens",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "cache_write_tokens",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column("cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index(
        "ix_token_events_extraction_id",
        "token_events",
        ["extraction_id"],
    )


def downgrade() -> None:
    # Reverse order of upgrade; FK dependencies drop cleanly.
    op.drop_index("ix_token_events_extraction_id", table_name="token_events")
    op.drop_table("token_events")

    op.drop_index("ix_qto_rows_extraction_division", table_name="qto_rows")
    op.drop_index("ix_qto_rows_trade_division", table_name="qto_rows")
    op.drop_index("ix_qto_rows_extraction_id", table_name="qto_rows")
    op.drop_table("qto_rows")

    op.drop_index("ix_extractions_user_status", table_name="extractions")
    op.drop_index("ix_extractions_user_id", table_name="extractions")
    op.drop_index("ix_extractions_pdf_id", table_name="extractions")
    op.drop_table("extractions")

    op.drop_index("ix_pdfs_project_id", table_name="pdfs")
    op.drop_table("pdfs")

    op.drop_index("ix_projects_user_id", table_name="projects")
    op.drop_table("projects")

    op.drop_table("users")
